# Generated by Django 4.1.7 on 2023-03-08 12:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Название/номер комнаты')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Стоимость за сутки')),
                ('reservation', models.PositiveSmallIntegerField(default=1, verbose_name='Кол-во мест')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Апартаменты',
                'verbose_name_plural': 'Апартаменты',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_of_booking', models.DateField(default=django.utils.timezone.now, verbose_name='Дата заезда')),
                ('end_of_booking', models.DateField(default=datetime.datetime(2023, 3, 9, 12, 46, 58, 382985, tzinfo=datetime.timezone.utc), verbose_name='Дата освобождения')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Статус')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.apartment', verbose_name='Комната')),
            ],
            options={
                'verbose_name': 'Резервация',
                'verbose_name_plural': 'Бронирования',
            },
        ),
    ]
